# Generated by Django 4.2.17 on 2025-01-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_comments_comment_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edgy',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
