# Generated by Django 4.2.17 on 2025-01-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_edgy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hate_speech',
            field=models.CharField(null=True),
        ),
    ]
