# Generated by Django 4.2.7 on 2025-01-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_is_hate_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
